name: branches

on:
  push:
    branches:
      - fix/*
      - feat/*

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v6
      - name: ğŸ¤– Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: ğŸ“¦ Bundle JS
        run: make prod
      - name: debug
        run: echo ${pwd} && echo ${ls -l}
      - name: ğŸ Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: ğŸ§° Install Poetry
        run: pip install poetry
      - name: ğŸ“¥ Install dependencies
        run: poetry install --with dev --with docs
      - name: ğŸ§ª Run tests
        run: poetry run pytest
      - name: ğŸ—ï¸ Build package
        run: poetry build
      